### ISSUE TITLE
Ayudantía Viernes 14 septiembre

### ISSUE THREAD

**Issue by marianaortega1** [IIC2143-2018-2/syllabus-1#3]
Hola!
No encontré un calendario de ayudantías así que quería preguntar si este viernes 14 de septiembre habrá ayudantía del ramo (considerando la fecha y además que hay entrega ese día). Gracias!

Saludos,
Mariana

**Comment by haroldmuller** [comment]
Hola Mariana!
Este viernes sí habrá ayudantía. El viernes 21 de Septiembre no habrá. Se avisará con anticipación las semanas que no hayan ayudantías.

Saludos,
